package Exaception;

public class Demo {
	public static void main(String []args)
	{
	try
	{
		int a=5,b=0;
		int c=a+b;
		int product=a*b;
		int sub=a-b;
		System.out.println(c);
		System.out.println(product);
		System.out.println(sub);
		int div=a/b;
		System.out.println(div);
	}
	catch(Exception e)
	{
		System.out.println(e);
	
		
	}
		
				
	
	}
	

}
